In [1]:
# Importing numpy
import numpy as np

In [2]:
# creating numpy array.
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [3]:
# creating 2-d array
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [5]:
print(b.ndim)
print(b.shape)

2
(2, 3)


In [6]:
print(b.ndim)
print(b.shape)

2
(2, 4)


In [6]:
c = np.arange(1,30,3)
print(c)

[ 1  4  7 10 13 16 19 22 25 28]


In [8]:
# using lispace - it prints the values based on the no.of points value between the array
d = np.linspace(1,10,3)
print(d)

[ 1.   5.5 10. ]


In [9]:
# common array -- > dimensions are given as inputs and it prints all 1 as values
e = np.ones((3,4))
print(e)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [10]:
f = np.eye(3,3) # it returns the identity matrix
print(f)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [11]:
# create array using diag function
g = np.diag([1,2,3,4])
print(g)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [12]:
h = np.random.rand(5) # creates an array of given shape and populates it with random samples 
print(h)

[0.22368769 0.73569363 0.18943244 0.94268473 0.63983567]


In [13]:
# creates an array of given shape and populates it with random samples from standard normal distribution
i = np.random.randn(5)
print(i)

[-0.99419398 -1.14634111 -1.31261148  0.78266973 -0.66414665]


In [14]:
# we can explicitly specify which data-type you want :
j = np.arange(10, dtype= 'float64')
print(j)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [15]:
k = np.zeros((3,3))
print(k)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


### Slicing

In [18]:
print(j) 
j[1:8:2] #[Startindex, EndIndex, StepSize]

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


array([1., 3., 5., 7.])

In [19]:
# updating values
j[5:] = 10
print(j)

[ 0.  1.  2.  3.  4. 10. 10. 10. 10. 10.]


In [21]:
# Assigning reverse of an array to a variable
b = np.arange(5)
j[5:] = b[::-1]
print(j)

[0. 1. 2. 3. 4. 4. 3. 2. 1. 0.]


In [22]:
k = np.arange(10)
l = k[::2]
print(l)

[0 2 4 6 8]


In [23]:
np.shares_memory(k,l)

True

In [24]:
l[0] = 52
print(l)

[52  2  4  6  8]


In [26]:
print(k)
# we can see that, when we update the 'l' variable it affected the 'k' variable as well because they both are using shared resources

[52  1  2  3  4  5  6  7  8  9]


In [29]:
# to avoid this we can use the copy function 
m = k[::2].copy()
m

array([52,  2,  4,  6,  8])

In [30]:
np.shares_memory(m,k)

False

In [1]:
a = 'hi'
b= 'hi'

In [2]:
a = 'hello'
print(a,b)

hello hi


In [3]:
a = [1,3,4]
b = [1,3,4]

In [4]:
import numpy as np
np.shares_memory(a,b)

False

In [5]:
a[0] = 3
print(a,b)

[3, 3, 4] [1, 3, 4]
