In [2]:
import numpy as np
a = np.array([1,2,3,4,5])
a+1

array([2, 3, 4, 5, 6])

In [3]:
a ** 2 # exponent 

array([ 1,  4,  9, 16, 25], dtype=int32)

In [4]:
c = np.diag([1,2,3,4])
print(c*c)
print('***********************')
print(c.dot(c))

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]
***********************
[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


In [8]:
x = np.array([[1,2],[4,5]])
x

array([[1, 2],
       [4, 5]])

In [9]:
x.sum(axis= 0) # Columns first dimension

array([5, 7])

In [10]:
x.sum(axis= 1) # rows second dimension

array([3, 9])

In [12]:
x.min()

1

In [13]:
x.max()

5

In [14]:
x.argmin() # prints the index of min value

0

In [15]:
x.argmax() # prints the index of max value

3

### Logical Operations

In [16]:
np.all([True,False,True,True]) # This is like 'and' operator

False

In [17]:
np.any([True,False,False,False]) # This is like 'OR' operator

True

In [27]:
a.T 

array([1, 2, 3, 4, 5])

## BroadCasting

#### basic operations(add, sub.. etc) on numpy arrays are element wise
#### This works on arrays of the samesize. nevertheless, it's also possible to do operations on arrays of different sizes.. if numpy can transform these arrays so that they all have the same size: this is called broadcasting

In [32]:
b = np.tile(np.arange(0,40,10),(3,1)) # Construct an array by repeating A the number of times given by reps.
print(b)
print('==============')
print(b.T)

[[ 0 10 20 30]
 [ 0 10 20 30]
 [ 0 10 20 30]]
[[ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]]


In [33]:
c = np.array([0,1,2])
c

array([0, 1, 2])

In [35]:
b.T + c ## it add the 'c' array values to all the rows.. 

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [36]:
d = np.arange(0,40,10)
d

array([ 0, 10, 20, 30])

In [37]:
d.shape

(4,)

In [38]:
d = d[:, np.newaxis] # adds a new axis - > 2 D array
d.shape

(4, 1)

In [39]:
d

array([[ 0],
       [10],
       [20],
       [30]])

In [41]:
## flatteing 
e = np.array([[1,2,3,4],[4,5,5,6]])
e.ravel()

array([1, 2, 3, 4, 4, 5, 5, 6])

In [42]:
e.T # Transposde

array([[1, 4],
       [2, 5],
       [3, 5],
       [4, 6]])

In [43]:
e.T.ravel()

array([1, 4, 2, 5, 3, 5, 4, 6])

In [44]:
e.shape

(2, 4)

In [45]:
e

array([[1, 2, 3, 4],
       [4, 5, 5, 6]])

In [47]:
# reshaping
e.reshape((4,2))

array([[1, 2],
       [3, 4],
       [4, 5],
       [5, 6]])